# Middleware package
from middleware.auth_middleware import role_required, login_required_custom
from middleware.audit_middleware import AuditMiddleware, log_request_middleware
from middleware.error_handler import register_error_handlers